### ISSUE TITLE
Pattern-matching algorithm is wrong near the word boundaries

### ISSUE THREAD

**Issue by yurivict** [mnater/Hyphenator#228]
Please note that Hyphenator splits the following English words wrong:
math·e·mat·ic·s (should be math·e·mat·ics)
al·go·rith·m (should be al·go·rithm)
toothaches (should be tooth·aches)
p·neu·mo·ni·a (should be pneu·mo·nia)

The first three words appear in the original Franklin Liang paper.

I looked into how the word 'pneumonia' is processed, and found that split of the first 'p' occurs due to the pattern '2p3n', and the split of the last 'a' occurs due to the pattern '2i1a'.

I believe patterns should only match at the middle of words when they don't start/end with the period symbol. Current implementation matches mid-word patterns even at the word boundaries, hence producing incorrect syllable split points.

See my pull request https://github.com/mnater/Hyphenator/pull/227 for the demo showing how syllables are being split.

**Comment by mnater** [comment]
Hi

Thanks for your thoughts. No offence, but I think you got some points wrong and I'd like to clarify (but maybe it's me, who is wrong;)

a) We don't do syllabification, we do hyphenation. These are mostly synonyms but there are some small differences:
- for hyphenation we don't need to find all possible word-breaking opportunities. It's ok to miss some of them (but it's not ok to find a false one)
- hyphenation points are mostly but not always between syllables

Example:
In German there was (is?) an ongoing discussion about how to hyphenate foreign words: between syllables or etymologically. When someone creates patterns for hyphenation he has to make a list of hyphenated words. If for a word hyphenation/syllabification isn't clear he will not split the word at this controversial point.
So for example the german word Helikopter is allowed to be syllabified (He-li-kop-ter) or to be split etymologically (He-li-ko-pter). In the list for pattern generation the author will most likely put He-li-kopter to avoid this discussion while missing one hyphenation opportunity…

Another source for missed hyphenation opportunities is the fact that the patterns were historically created for machines with very low capabilities (every byte matters). So that's probably the case why 'toothache' isn't hyphenated by the current patterns. If you find some modern neat patterns, please let me know (for German there is http://projekte.dante.de/Trennmuster/WebHome)

b) You shouldn't just change leftmin and rightmin to 0 (or 1). These values are part of the algorithm. They are used upon pattern creation and thus must be handled as a part of the patterns. (That's also why there isn't an API in Hyphenator to change them.) So IMHO there isn't an error – it's a misconfiguration.
(See the man page for patgen in your TeX installation or on http://linux.die.net/man/1/patgen)

c) Because of b) the mid-word patterns have to match at word boundaries, too. See e.g. the patterns for the word 'hyphenation' (use http://mnater.github.io/Hyphenator/testsuite/test108.html) The pattern 'hy3ph' matches at the beginning of the word giving us the first hyphenation point.

That's my view, let me know, if I'm wrong.

**Comment by yurivict** [comment]
Thank you for clarifying this. I was first under impression that hyphenation is supposed to be close to syllable splitting, therefore ideally leftmin/rightmin should ideally be 0. But this isn't the case.

Thank you!
