### ISSUE TITLE
Hyphenator adding class in chrome, hyphen not appearing

### ISSUE THREAD

**Issue by tiki16** [mnater/Hyphenator#236]
Hi I am using hyphenator and it is working fine in firefox, ie 10, 11 and safari on windows. However in Chrome Version 45.0.2454.93 m the hyphen isn't appearing. When I view the code I can see the class I added but there is another one being injected into the class like so:
`<div class="hyphen Hyphenator321hide">Accommodation</div>`

Why is it adding the "Hyphenator321hide" class name? Oddly enough the number changes when the page is refreshed. 
Thanks
Steve

**Comment by mnater** [comment]
Hi

The injected class `Hyphenator321hide` hides the element while it is hyphenated (so there's only one repaint instead of a repaint after each word getting hyphenated). The number changes randomly for each pageload. So if a site coincidentally uses the same class name it will be different after a reload and the site can be displayed correctly (which will almost never happen).

If Hyphenator ran correctly this class should have been removed at the end. It wasn't so there's an issue.
Could you please post a link to a site where this happens or some code that helps me reproduce the issue?

Thanks,
Mathias

**Comment by tiki16** [comment]
Hi Mathias, It is on a staging server. I'll have to get it up to an accessible server. Probably my own, which means later tonight.
thanks
Steve

**Comment by tiki16** [comment]
Also an fyi, it works in chrome on my desktop pc, but not on my laptop in chrome. There are 2 other people it did not work in chrome on their desktops.
thanks

**Comment by tiki16** [comment]
I changed the initialisation script to the on in the example and using hyphenator.js without hylo.js and it works now.
