### ISSUE TITLE
How many syllables are in a text

### ISSUE THREAD

**Issue by sensei71** [mnater/Hyphenator#237]
I'm programming a plugin to get the readability of a text. I need to know How many syllables are in a multi language text. It will be useful to implement a function to get this.

Regards

Rodolfo
rodolfooliva@gmail.com

**Comment by mnater** [comment]
Hi

The hyphenation patterns won't necessary find all syllables, they find possible hyphenation points.

For example the german word "beinhalten" (to contain) has 4 syllables "be-in-hal-ten" but only 3 hyphenation points "be-inhal-ten" since a hyphenation like "bein-halten" is misleading (to hold a leg).

So using Hyphenator.js (the TeX hyphenation algorithm in general) to count syllables will not result in an exact count but in an approximation.

If an approximation is good enough, use [Hyphenator.hyphenate()](https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#mixed-hyphenatorhyphenatemixed-target-string-lang) to hyphenate a string, then use String.split() to split at spaces and `hyphenchar` and get the length of the resulting array.

Regards,
Mathias

**Comment by mnater** [comment]
Something like this (quick and dirty):
```javascript
Hyphenator.config({hyphenchar: "-"});

function approxSyllableCount(text, lang) {
	var hyphenatedText = Hyphenator.hyphenate(text, lang);
	var splitted = hyphenatedText.split(/ |-/g);
    return splitted.length;
}

var text = document.getElementById('text').innerText;
var count = approxSyllableCount(text, "en");
console.log(count);
```

**Comment by sensei71** [comment]
Thank you for your reply.
