### ISSUE TITLE
Hyphenator_loader does not work on Mobile Opera Browser on Android

### ISSUE THREAD

**Issue by tmb-github** [mnater/Hyphenator#243]
I'm using the Hyphenator_loader to detect whether the browser already has built-in CSS hyphenation and then load the Hyphenator if not. This works on all the major desktop browsers on Windows (Chrome, Firefox, Opera, IE, Edge, etc.) and on all of the corresponding mobile versions of those browsers on my Droid phone and tablet (including browsers like Dolphin and CM) *EXCEPT* for Opera Mobile. Apparently, the Hyphenator_loader incorrectly concludes that CSS hyphenation is supported on Opera Mobile (=Mini?), and therefore does not load the Hyphenator. This isn't the case with the desktop version of Opera for Windows. I've therefore had to write a routine to check whether my site is running on Opera Mobile, and if so, then bypass the Hyphenator_loader and load the Hyphenator directly. (I find this especially strange because Mobile Chrome doesn't have this problem, and yet Chrome and Opera are the two browsers that still have not implemented CSS hyphenation.) I'm happy to provide additional information to help reproduce this problem and fix it, for I'm very happy with the Hyphenator. Many thanks!

**Comment by mnater** [comment]
Hi

Thanks for the report.

I don't own a Android device, but I was able to reproduce the issue on Opera Mini for iPhone.

Looks like Opera Mini has different modes: mini, turbo, off (tab on the opera button at the bottom, then tab the graph showing how much data you saved to change the mode). The issue only occurs in "mini" mode for me.

I don't know yet what Opera does to JavaScripts in the background and it's very hard to debug.

**Comment by tmb-github** [comment]
Thanks so much for checking on this! I'm glad you were able to reproduce
the problem, which confirms that it wasn't a coding problem on my website.
I hope you'll be able to debug this, as many people do use Opera.

I couldn't find the mode switching on the Android version of Opera (perhaps
mine is a dedicated "mini" version; I'll research that.)

I must say, what you have created is far superior to what is natively
available in Firefox and IE/Edge. I especially appreciate the ability to
add lists of additional words with special hyphenations.

One thing that may be an oversight: If I create an all-in-one
Hyphenator.js, and if I only specify English (or any one language), the
resulting code includes error messages and test strings in apparently *all*
the supported languages, rather than just in the language (or languages)
being specified. I manually stripped out the apparently unnecessary
language code that didn't pertain to my hyphenation needs on my site. I may
not understand why the other language samples are included in the opening
section of the auto-generated Hyphenator.js, but if they are not needed,
you could reduce the size of the file by eliminating all but the
language(s) selected by the user in the mergeAndPack application.

Many, many thanks for creating this very useful tool.

Tom

**Comment by mnater** [comment]
I did some further research:
Websites accessed by Opera Mini are processed and rendered on Opera's Servers and only a highly optimised version of the website is sent to the Opera Mini Browser on the client; it's not even HTML it's Opera Binary Markup Language (OBML)… (See https://dev.opera.com/articles/opera-mini-and-javascript/)

So JavaScripts are processed on this servers, that's fine, but OBML doesn't seem to support soft hyphens – and all Hyphenator.js does is to put these soft hyphens at the right positions. Soft hyphens don't work in OBML even if inserted manually.
Therefor I can't fix this, sorry.
Opera Turbo Mode works differently: Rendering happens on the device rather then the server. That's why Hyphenator works in Turbo Mode. (See https://dev.opera.com/blog/opera-mini-8-for-ios/)

About the error messages in different languages.
That's not an oversight. I'm for instance surfing on english websites using Hyphenator.js as a bookmarklet but my systems language is set to german. I'll get error messages in german on all websites regardless of their language.
That's nice but not absolutely necessary – feel free to delete these lines in your copy (happen to be one-liners for this case ;-)

Regards,
Mathias

**Comment by mnater** [comment]
Extreme mode doesn't support soft hyphens.
Opera says for "High" mode: "View sites how they were intended"
For "Extreme" mode there's no such sentence.
