### ISSUE TITLE
pattern format

### ISSUE THREAD

**Issue by eroux** [mnater/Hyphenator#256]
I would like to convert some patterns to the javasript pattern format you're using, but I cannot find any documentation nor conversion script. Can you please provide some details or add some pointers to the documentation?

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenator/blob/wiki/en_PatternFilesFormat.md

**Comment by eroux** [comment]
Thanks a lot!

**Comment by eroux** [comment]
Sorry, one more related question, how are `patternArrayLength` and `valueStoreLength` supposed to be computed?

**Comment by eroux** [comment]
Other point not very clear in the doc:

- in the pattern string, I guess `_` is what replaces the `.` of pat patterns?
- what is the length of the `1-1` pattern? 0 or 1? should `-` appear in patternChars?
- what is the length of the `.a2d1` pattern? 2 or 3? (should the `.` be counted in the length?)

**Comment by eroux** [comment]
After looking at the code of `compressor.html`, I think it's just too difficult to implement, I'll just use it...

**Comment by mnater** [comment]
`patternArrayLength` and `valueStoreLength` are computed by building a pattern-trie with dynamic arrays whose lengths are measured at the end. Hyphenator.js uses preallocated typed arrays for the pattern-trie and thus requires those lengths.

I use `_` instead of `.` in the patterns to denote the difference from LaTeX patterns.
The length of the patterns includes the values. So `.a2d1` has a length of 5, `1-1` has a length of 3.
(`1-1` really doesn't make sense as a pattern. Clients already break lines after a `-`. Hyphenator.js recognizes words containing a `-` and hyphenates the parts separately.)

I'll updated the docs to make this clearer.
And, yes, those tools should be npm modules.

**Comment by eroux** [comment]
Thanks for the answers and the doc clarification! Closing it, no point in keeping this open.
