### ISSUE TITLE
No line breaks at existing hyphen

### ISSUE THREAD

**Issue by GutHib** [mnater/Hyphenator#261]
Hi,

I've noticed an odd bug: Hyphenator won't do a line break in words with an existing hyphen, if the part after the hyphen is shorter than six characters. You can use the following as dummy, or an actual word instead:

xxxxxxxxx-yyyyy

Thanks!

**Comment by mnater** [comment]
That's because each part of the compound word is treated as a discrete word where the minwordlength-setting inhibits hyphenation.
Yes, its a bug if you count all characters of the compound word (Hyphenator.js currently counts the chars of each part of the compound word).

I'm not sure if I should fix that since hyphenations like
````
high-le-
vel
````
are very ugly.

Instead I'd rather increase required length of the parts to inhibit such ugly line-breaks.
What do you think?

**Comment by GutHib** [comment]
Right. It's the ugliness of examples like the one you posted that made me come here. :)

So yes, anything you can do to prevent this would be fantastic. But to be honest, I don't quite understand the explanation: If "level" in your example was treated as a discrete word, wouldn't the minwordlength-setting actually keep it from being separated like this? And to me it also doesn't explain why a world like reallyreallylong-level still won't do a line break at the hyphen.

**Comment by mnater** [comment]
> anything you can do to prevent this would be fantastic

Should be possible…

> If "level" in your example was treated as a discrete word, wouldn't the minwordlength-setting actually keep it from being separated like this?

That's the current behaviour.

> And to me it also doesn't explain why a world like reallyreallylong-level still won't do a line break at the hyphen.

Afaik, all engines automatically break after a (hard) hyphen if necessary. But I'll have to test it.
If not, Hyphenator.js could insert a zero-width space after such a hyphen…

I'm currently pretty occupied, so implementing this will take a while. I'll report back here.

Thanks and regards,
Mathias

**Comment by GutHib** [comment]
Ok, now I realize the misunderstanding. As a matter of fact, high-level will NOT break after a hard hyphen, no matter what you throw at it.

Current behavior:

```
high-le-
vel
```

Desirable, but currently not possible:
```
high-
level
```
I also tested this by downloading the latest Hyphenator-master from Github. Edited WorkingExample.html. No cigar.

**Comment by mnater** [comment]
Huh! Engines behave different here:
- Webkit (Safari and Chrome) break lines after a hyphen-minus. But I just had to file a bug: https://bugs.webkit.org/show_bug.cgi?id=157523
- Firefox doesn't break after a hyphen-minus.
- IE 8-9 are buggy, IE 7 OK
- IE 10, 11 are OK
- Edge is OK

**Comment by GutHib** [comment]
Yeah, I can confirm the behavior with Firefox and Edge. Wow - it never ocurred to me that this might be browser-specific! So is this a Firefox bug then, or is it a *cough* feature?

**Comment by mnater** [comment]
Obviously it is not specified if UAs should break after a '-'. I didn't find a clue in the specs.

So I added a new config property called `compound`
E.g.:
````javascript
Hyphenator.config({compound: 'hyphen'});
````
This inhibits hyphenation of parts before and after the '-' in a compound word and adds a zero width space (&amp;#8203;) after the '-'.

All possible settings are:
- `compound: 'auto'` factory-made -> fac&amp;shy;tory-made (this is the old behavior and the default for compatibility)
- `compound: 'all'` factory-made -> fac&amp;shy;tory-&amp;#8203;made
- `compound: 'hyphen'` factory-made -> factory-&amp;#8203;made

(in this examples 'made' will never be hyphenated, because it's too short).

**Comment by GutHib** [comment]
Sounds great. The icing on the cake would be a setting that prioritizes the hard hyphen and will only add additional breaks where unavoidable. Says someone who mainly uses Hyphenator for blog headlines. So a word like factory-made would NOT break like this in a really long line:

```
fac-
tory-made
```

...where it would look silly, but on a small screen with large letters, it could still do:

```
fac-
tory-
made
```

(And yes, I realize that may be too much asked for, but hey - in a perfect world...)

**Comment by mnater** [comment]
There's now way in JS to see where a line break actually occurs.

The only solution I can think of is to implement settings on a per class basis – i.e. one could define settings for a title class and settings for a floating-text class etc.

If never thought of this before, but it seems to be the natural way to do it, since CSS works the same…

But I'm not going to implement this in Hyphenator.js anymore. I'm currently working on a more lightweight solution (https://github.com/mnater/Hyphenopoly) for current browsers which is still in an early beta. Class-based settings will be implemented there.

Thanks and regards,
Mathias

**Comment by GutHib** [comment]
Got it. Thanks again for you quick replies and the action taken.

**Comment by GutHib** [comment]
So... I took this for a test run, and here's the verdict: The "all" setting is a definite improvement, as it takes the previous behavior and adds the line breaks at existing hyphens (for Firefox).

But unlike what you wrote above, each part of the compound word is NOT treated as a discrete word. In other words, you will get:

```
high-
le-
vel
```

...despite the shortness of "level", and there's really no good way to keeping this from happening. If you put "level" onto the list of unbreakable words, it's ignored, and adding "high-level" (that would be my favorite!) doesn't do anything either. Virtually the only way to stop it now is to set "hyphen" to "compound", but while that'll work for "high-level", it's gonna spell trouble for the next occurrance of "incomprehensibility-level". ;)

**Comment by mnater** [comment]
Thanks. Silly me.
Fixed in https://github.com/mnater/Hyphenator/commit/064eeff9dcea5018f300fb82027e3f2c5516ebb7

**Comment by GutHib** [comment]
Rocks.
