### ISSUE TITLE
Re-Running Hyphenator with Hyphenator-Loader

### ISSUE THREAD

**Issue by FranzSkuffka** [mnater/Hyphenator#262]
I am working on an SPA that leverages hyphenator. I need to re-run hyphenator whenever I load a content page. When I use  the Loader, the Hyphenator object is not available globally anymore and there is no callback API provided to pass a function to the loader to execute after loading.

Can anyone recommend an approach?

**Comment by mnater** [comment]
The Hyphenator object should be available when Hyphenator_Loader has decided, that Hyphenator.js is needed and the script is loaded. In an SPA this normally happens once on the first page load.
So, for subsequently loaded content (I assume that only the body of the page changes) the Hyphenator object should be available if needed and thus you can use Hyphenator.hyphenate(target, lang).
But may be I'm wrong (I haven't tested this, yet)?

PS: Wir können auch auf Deutsch weitermachen…

**Comment by FranzSkuffka** [comment]
I was playing around a little and when I looked at the source code I realized that the appended `script`-tag is removed after Hyphenator has run. It is not available globally afterwards. What I ended up doing was caching the results of Hyphenator and loading it whenever I was opening that view again.

My main issue is that the global Hyphenator object is not exposed when using the loader, but correct me if I'm wrong.

Let's stick with English so that others can follow-up. Tech stuff is just so much easier in English.

**Comment by mnater** [comment]
I pushed a new test that mimics the situation: http://mnater.github.io/Hyphenator/testsuite/test124.html

1. It runs Hyphenator_Loader.js to check if Hyphenator.js is needed and runs Hyphenator.js to hyphenate the texts with red backgrounds (only in Chrome, since all other browsers support CSS-hyphens natively. If Hyphenator.js is in charge the hyphen character is a pipe "|", if text gets hyphenated by the browser, you'll just see hyphenated words – resize the window, if necessary).
2. 2 seconds after the pageload-event it updates the text under "Test2" and hyphenates it, by calling Hyphenator.hyphenate() if the Hyphenator object is available (i.e. if Hyphenator.js had been loaded because there's no native support for the given language in the browser).

I double checked with a language where none of the browsers support native hyphenation (Armenian for instance: http://127.0.0.1/~mnater/Hyphenator/testsuite/test95.html
In all cases and in all major browsers (IE/Edge, Chrome, Safari, Firefox) the Hyphenator object is exposed (simply type `Hyphenator` in the dev tools console and hit return).

So either you're testing with a browser that supports the language of your page and Hyphenator.js is never loaded (and thus not available) or something else deletes the object.

Now that I can't reproduce the issue myself: could you provide me with some code that shows the bug?
