### ISSUE TITLE
Different syllabification results with Hyphenator Javascript and greek-accentuation Python library

### ISSUE THREAD

**Issue by markomanninen** [mnater/Hyphenator#273]
I wanted to compare results with Hyphenator javascript library and greek-accentuation Python libraries for Greek Revelation text statistics. 

With Hyphenator I used minwordlength: 1 and 2 and hyphenchar: '-'. I didn't see any difference when using min right/left values.

With Python library there aren't any special settings to be used.

My results are for the first 14 rows each consisting of 16 syllables:

**Hyphenator (Javasacript):**

απο-κα-λυ-ψις ιη-σου χρι-στου ην εδω-κεν αυ-τω ο θε-ος
δει-ξαι τοις δου-λοις αυ-του α δει γε-νε-σθαι εν τα-χει και
εση-μα-νεν απο-στει-λας δια του αγ-γε-λου αυ-του τω δου-λω
αυ-του ιω-αν-νη ος εμαρ-τυ-ρη-σεν τον λο-γον του θε-ου
και την μαρ-τυ-ρι-αν ιη-σου χρι-στου οσα τε ει-δεν μα-κα-
ρι-ος ο ανα-γι-νω-σκων και οι ακου-ον-τες τους λο-γους της
προ-φη-τει-ας και τη-ρουν-τες τα εν αυ-τη γε-γραμ-με-να
ο γαρ και-ρος εγ-γυς ιω-αν-νης ταις επτα εκ-κλη-σι-αις ταις
εν τη ασια χα-ρις υμιν και ει-ρη-νη απο του ο ων και ο
ην και ο ερ-χο-με-νος και απο των επτα πνευ-μα-των α εστιν
ενω-πι-ον του θρο-νου αυ-του και απο ιη-σου χρι-στου ο μαρ-
τυς ο πι-στος ο πρω-το-το-κος εκ των νε-κρων και ο αρ-
χων των βα-σι-λε-ων της γης τω αγα-πη-σαν-τι ημας και λου-
σαν-τι ημας απο των αμαρ-τι-ων ημων εν τω αι-μα-τι αυ-του

...

_Total 1121 syllables_

**Syllabbify (Python):**

α-πο-κα-λυ-ψις ι-η-σου χρι-στου ην ε-δω-κεν αυ-τω
ο θε-ος δει-ξαι τοις δου-λοις αυ-του α δει γε-νε-σθαι εν
τα-χει και ε-ση-μα-νεν α-πο-στει-λας δι-α του αγ-γε-
λου αυ-του τω δου-λω αυ-του ι-ω-αν-νη ος ε-μαρ-τυ-
ρη-σεν τον λο-γον του θε-ου και την μαρ-τυ-ρι-αν ι-η-
σου χρι-στου ο-σα τε ει-δεν μα-κα-ρι-ος ο α-να-γι-
νω-σκων και οι α-κου-ον-τες τους λο-γους της προ-φη-τει-ας
και τη-ρουν-τες τα εν αυ-τη γε-γραμ-με-να ο γαρ και-ρος
εγ-γυς ι-ω-αν-νης ταις ε-πτα εκ-κλη-σι-αις ταις εν τη
α-σι-α χα-ρις υ-μιν και ει-ρη-νη α-πο του ο ων
και ο ην και ο ερ-χο-με-νος και α-πο των ε-πτα πνευ-
μα-των α ε-στιν ε-νω-πι-ον του θρο-νου αυ-του και α-
πο ι-η-σου χρι-στου ο μαρ-τυς ο πι-στος ο πρω-το-το-
κος εκ των νε-κρων και ο αρ-χων των βα-σι-λε-ων της γης
τω α-γα-πη-σαν-τι η-μας και λου-σαν-τι η-μας α-πο
των α-μαρ-τι-ων η-μων εν τω αι-μα-τι αυ-του και ε-

...

_Total 1241 syllables_

My question is, should I use Hyphenator for syllabification purposes for Ancient Koine Greek and how accurate results I can get with it?

**Comment by mnater** [comment]
Short answer:
No, you won't get accurate results.

Longer explanation:
Hyphenator.js finds (some) potential inner-word break points. These often coincide with syllable, but not always.

There are two reasons:

1. Single letter syllables at the beginning and the end of a word are omitted.
   Otherwise you'll get ugly hyphenation like

   ταχει και ε-
   σημανεν α-
   ποστειλας δι-
   α του αγγελου
   
   A minimum number of letters (two letters for greek) for each part is hardcoded in the patterns (leftmin and rightmin) and can't be changed without recomputation of the patterns.

2. The hyphenation algorithm prefers to miss some break points instead of generating false positives.
